import 'package:flutter/widgets.dart';

// NOTE: this file is generated by `flutter gen-l10n` (configured in l10n.yaml)
// from the ARB files in arb/. It will not exist until you run `flutter pub get`
// / build once. See README.
import 'generated/app_localizations.dart';

export 'generated/app_localizations.dart';

/// Ergonomic accessor: `context.l10n.appName`.
extension L10nContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
